### ISSUE TITLE
Questao 2545

### ISSUE THREAD

**Issue by AlbertoLucass** [lclpsoz/competitive-programming#1]
Ola Lucas. Seria possivel vc localizar a questão 2545 manyfile do uri, por favor?! Eu consegui rodar alguns testes mas não passaram em todos. E tb, o seu repo foi o mais organizado q achei.
Ou então mande para o meu email alberto.trindade@ufba.br. Obrigado.

**Comment by lclpsoz** [comment]
Opa, Alberto. Segue o link do arquivo: [2545.cpp](https://github.com/lclpsoz/competitive-programming/blob/master/ARCHIVE/2019-06-05-2000/2545.cpp). Estava em uma das pastas arquivadas de antes de eu começar a organizar.

Fico feliz em saber que o repo está sendo útil. Qualquer coisa é só mandar.

**Comment by AlbertoLucass** [comment]
Brigadão Lucas. Percebi que vc ta fazendo parecido comigo. Na verdade, acho que o maior problema não é a questão em si, mas o python. To aprendendo python e queria fazer com ele, mas ele trata os dados de uma maneira diferente do c/c++. O seu código ta bem mais limpo e bonito, obviamente kk. To tentando implementar o seu primeiro em python, pra depois tentar o meu.

**Comment by AlbertoLucass** [comment]
Eu tentei fazer aqui a [sua](https://github.com/AlbertoLucass/atividades/blob/main/teste.py), até deu certo para o caso de teste que tem lá, porém ta dando tle, e realmente não to conseguindo. Porém vou continuar fim de semana a dentro. A sintaxe ta me quebrando kkk

**Comment by AlbertoLucass** [comment]
Cara, eu acho que to quase la. Ao rodar com o primeiro caso de teste(o exemplo 0) da [maratona da ufpr](https://www.inf.ufpr.br/maratona/interna/7a-seletiva-2016/inout/manyfile/). As saidas estao saindo conforme a imagem abaixo.
Vou ver se termino isso ainda hj, ate pq a lista so vai ate amanha. A esquerda o seu em c++, a direita uma versao do seu em python, ou uma tentativa kk. Eu coloquei pra printar os valores de 'qnt' e 'ans'.

![img](https://user-images.githubusercontent.com/38790522/133912074-238b0a72-ef83-4b37-bd2d-bf09cd4559e0.png)

**Comment by lclpsoz** [comment]
Só toma cuidado com TLE em Python, como ele é bem mais lento pode ser que seu código esteja o melhor possível, mas a linguagem acabe inviabilizando o AC. URI vêm se esforçando para aumentar os TLs de Python, mas nem sempre é viável.

**Comment by AlbertoLucass** [comment]
Sim. Testei com varias entradas la do site da ufpr, e bateu, mas no uri ta dando tle. Bad :/
